Sdl2 OpenGL Hotreload Demo
odin-lang/examples pull request #65
Opened 2024-12-22 00:19 UTC by novicearts

This PR modifies the existing SDL2/OpenGL demo to also include rudimentary hot reloading. This works by changing the game package code and recompiling the game dll using `build_game_dll.bat`. This is dependent on a working odin environment setup beforehand though.

- [x] Have you added the example to the CI at `.github/workflows/check.yml`?

2025-01-12 23:27 UTC, karl-zylinski requested changes
Thank you for your PR.

Please see my comments about the issues I see.

2025-01-12 23:27 UTC, karl-zylinski commented on sdl2/opengl_hotreload/build_game_dll.bat
> +%odin% build game -build-mode:shared -out:game.dll -debug
%odin% is not a common environment variable. Just write `odin` and assume people have it in PATH.

2025-01-12 23:27 UTC, karl-zylinski commented on sdl2/opengl_hotreload/main/sdl2_main.odin
> +    // TODO: this presently requires windows CLI tool 'copy' to work, for cross platform support, we can select the right command by OS
You can use `os2.copy_file` for now

2025-01-12 23:27 UTC, karl-zylinski commented on sdl2/opengl_hotreload/common/sdl2_common.odin
I would not have this as a separate package. It encourages splitting things into many small packages, which is perhaps not what we want in `examples`. Instead I would move all these things to `game` and make `main` agnostic of what game does.

2025-01-12 23:27 UTC, karl-zylinski commented on sdl2/opengl_hotreload/main/sdl2_main.odin
This file mixes tabs and spaces. All examples should use tabs for indentation.

2025-01-12 23:27 UTC, karl-zylinski commented on sdl2/opengl_hotreload/main/sdl2_main.odin
Make the main file not use SDL at all and make it not know anything of game. When you do that you can remove the "common" package.

2025-01-12 23:27 UTC, karl-zylinski commented on sdl2/opengl_hotreload/stub.odin
Why is this file here? Is it to make it pass the tests, since a bat file needs to run?

2025-01-12 23:27 UTC, karl-zylinski commented on sdl2/opengl_hotreload/stub.odin
You can do `odin check <each_package>` multiple times. For packages without a main proc you can add `--no-entry-point`. Try running the check on your computer to see what you need to run.

2025-01-12 23:27 UTC, karl-zylinski commented on sdl2/opengl_hotreload/main/sdl2_main.odin
> +        should_not_quit := platform_input()
Very strange "backwards bool". Isn't it better if `sdl2_game.odin` handles all the input and just returns a bool when you run `update`?

2025-01-14 05:11 UTC, novicearts commented on sdl2/opengl_hotreload/main/sdl2_main.odin
> +    // TODO: this presently requires windows CLI tool 'copy' to work, for cross platform support, we can select the right command by OS
noted. which version of the odin compiler was `os2.copy_file` added for? I opted for the present approach in case there were people using slightly older versions of the compiler (like myself, b/c I have dependencies locked for a few projects)

2025-01-14 05:13 UTC, novicearts commented on sdl2/opengl_hotreload/stub.odin
Admittedly yes this was to make the check pass (it was failing b/c it couldnt find a file at the top level with main defined, even though my example instead separately defines 2 main packages, one for hot reload, and one for standard build).
I'll revisit the `odin check` configuration for `check.yml`

2025-01-14 05:18 UTC, novicearts commented on sdl2/opengl_hotreload/common/sdl2_common.odin
if I understand the structure correctly, main should hold nothing but the pointer to all of game's data (an opaque pointer most likely), which game would transmute into its preferred structure on reload. Is that the right way to look at it? 

I'm thinking that's the main mechanism needed to remove SDL2 from `main`

2025-01-14 11:09 UTC, karl-zylinski commented on sdl2/opengl_hotreload/main/sdl2_main.odin
> +    // TODO: this presently requires windows CLI tool 'copy' to work, for cross platform support, we can select the right command by OS
I was mostly thinking so that it works cross-platform. But I realize now that this is all windows-specific. I think its a bit weird to use SDL but then also be windows-specific.

2025-01-16 01:20 UTC, novicearts commented on sdl2/opengl_hotreload/main/sdl2_main.odin
> +    // TODO: this presently requires windows CLI tool 'copy' to work, for cross platform support, we can select the right command by OS
that's a good point. I may need to revisit some of the platform code to ensure it works cross platform. But I suspect I will need platform specific files (for instance when supplying the name of the DLL, windows takes `.dll`, whereas linux takes `.so`)

2025-01-22 12:12 UTC, closed without merging